insert into teams(id, name) values
	--equipos mundial
	(0,"Rusia"),
	(0,"Arabia Saudita"),
	(0,"Egipto"),
	(0,"Uruguay"),
	(0,"Portugal"),
	(0,"Espana"),
	(0,"Marruecos"),
	(0,"Iran"),
	(0,"Francia"),
	(0,"Australia"),
	(0,"Peru"),
	(0,"Dinamarca"),
	(0,"Argentina"),
	(0,"Islandia"),
	(0,"Croacia"),
	(0,"Nigera"),
	(0,"Brasil"),
	(0,"Suiza"),
	(0,"Costa Rica"),
	(0,"Serbia"),
	(0,"Alemania"),
	(0,"Mexico"),
	(0,"Suecia"),
	(0,"Corea del Sur"),
	(0,"Belgica"),
	(0,"Panama"),
	(0,"Tunez"),
	(0,"Inglaterra"),
	(0,"Polonia"),
	(0,"Senegal"),
	(0,"Colombia"),
	(0,"Japon"),

	--saf 33-48
	(0,"Argentinos Juniors"),
	(0,"Boca Juniors"),
	(0,"River Plate"),
	(0,"Racing Club"),
	(0,"San Lorenzo"),
	(0,"Independiente"),
	(0,"Lanus"),
	(0,"Estudiantes"),
	(0,"Banfield"),
	(0,"Godoy Cluz"),
	(0,"Belgrano de Cordoba"),
	(0,"Talleres"),
	(0,"Gimnasia y Esgrima de la Plata"),
	(0,"Rosario Central"),
	(0,"Huracan"),
	(0,"Newell's Old Boys"),

	--CopaLibertadores 49-71
	(0,"Alianza Lima"), 
	(0,"Junior"),
	(0,"The Strongest"), 
	(0,"Millonarios"),
	(0,"Monagas"), 
	(0,"Defensor Sporting"),
	(0,"Nacional"),
	(0,"Real Garcilaso"),
	(0,"Gremio"), 
	(0,"Libertad"),
	(0,"Colo-Colo"),
	(0,"Flamengo"),
	(0,"Cruzeiro"), 
	(0,"Corinthians"),
	(0,"Atletico Tucuman"),
	(0,"Atletico Nacional"),
	(0,"Cerro"), 
	(0,"Palmeiras"),
	(0,"Santos"), 
	(0,"Deportivo Lara"),
	(0,"Penarol"), 
	(0,"Universidad de Chile"), 
	(0,"Vasco da Gama"); 



