insert into teams(id, name) values
	(0,"Rusia"),
	(0,"Arabia Saudita"),
	(0,"Egipto"),
	(0,"Uruguay"),
	(0,"Portugal"),
	(0,"Espana"),
	(0,"Marruecos"),
	(0,"Iran"),
	(0,"Francia"),
	(0,"Australia"),
	(0,"Peru"),
	(0,"Dinamarca"),
	(0,"Argentina"),
	(0,"Islandia"),
	(0,"Croacia"),
	(0,"Nigera"),
	(0,"Brasil"),
	(0,"Suiza"),
	(0,"Costa Rica"),
	(0,"Serbia"),
	(0,"Alemania"),
	(0,"Mexico"),
	(0,"Suecia"),
	(0,"Corea del Sur"),
	(0,"Belgica"),
	(0,"Panama"),
	(0,"Tunez"),
	(0,"Inglaterra"),
	(0,"Polonia"),
	(0,"Senegal"),
	(0,"Colombia"),
	(0,"Japon");